// Regenerated by Assets/Editor/BuildInfoGenerator.cs before every player build
// (all platforms). Editor Play mode does not update it, so the values describe
// the last real build, not the last time the project was opened. "dev" is the
// checked-in placeholder the generator restores after a build.

namespace HeatonCAApp
{
    /// <summary>
    /// Build stamp shown on the About page: when the player was built and the
    /// store build number it carries. Both are "dev" in the Editor.
    /// </summary>
    public static class BuildInfo
    {
        /// <summary>UTC build time, e.g. "2026-09-02 14:03 UTC", or "dev".</summary>
        public const string BuildTimeUtc = "dev";

        /// <summary>Store build number (HEATONCA_BUILD_NUMBER), or "dev".</summary>
        public const string BuildNumber = "dev";
    }
}
