/*
 * Cross-engine conformance: replay conformance/vectors.txt against the
 * optimized C engine. The vectors are generated by the Python reference
 * implementation; the JS and Java suites replay the same file. See
 * conformance/README.md for the contract (LCG initial lattice, FNV-1a 64
 * hash of the final lattice, both defined there).
 *
 * The LCG and hash below are independent implementations of that spec on
 * purpose -- only the engine under test is shared code.
 */
#include "../src/mergelife.h"

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Spec PRNG: 32-bit LCG, one byte (state >> 24) per advance, row-major RGB. */
static void lcg_fill(uint8_t *dst, uint32_t seed, size_t n) {
  uint32_t state = seed;
  for (size_t i = 0; i < n; i++) {
    state = state * 1664525u + 1013904223u;
    dst[i] = (uint8_t)(state >> 24);
  }
}

/* Spec hash: FNV-1a 64-bit, 16 lowercase hex digits. */
static uint64_t fnv1a64(const uint8_t *data, size_t n) {
  uint64_t h = 0xcbf29ce484222325ULL;
  for (size_t i = 0; i < n; i++) {
    h = (h ^ data[i]) * 0x100000001b3ULL;
  }
  return h;
}

static FILE *open_vectors(int argc, char **argv) {
  if (argc > 1) return fopen(argv[1], "r");
  /* The Makefile runs this from c/, but be forgiving about the cwd. */
  static const char *candidates[] = {
      "../conformance/vectors.txt",
      "conformance/vectors.txt",
      "../../conformance/vectors.txt",
  };
  for (size_t i = 0; i < sizeof(candidates) / sizeof(candidates[0]); i++) {
    FILE *f = fopen(candidates[i], "r");
    if (f) return f;
  }
  return NULL;
}

int main(int argc, char **argv) {
  FILE *f = open_vectors(argc, argv);
  if (!f) {
    fprintf(stderr, "conformance: cannot find conformance/vectors.txt "
                    "(pass the path as the first argument)\n");
    return 1;
  }

  int vectors = 0, failures = 0;
  char line[256];
  while (fgets(line, sizeof(line), f)) {
    char rule[64], expected[32];
    int rows, cols, steps;
    unsigned seed;
    if (line[0] == '#' || line[0] == '\n') continue;
    if (sscanf(line, "%63s %d %d %u %d %31s", rule, &rows, &cols, &seed,
               &steps, expected) != 6)
      continue;
    vectors++;

    MlGenome genome;
    if (ml_genome_parse(rule, &genome) != 0) {
      printf("FAIL  %s  (unparseable rule)\n", rule);
      failures++;
      continue;
    }
    MlRule mlrule;
    ml_rule_compile(&genome, &mlrule);

    MlGrid grid;
    if (ml_grid_init(&grid, rows, cols)) {
      fprintf(stderr, "conformance: grid alloc failed\n");
      fclose(f);
      return 1;
    }
    size_t n = (size_t)rows * cols * 3;
    lcg_fill(grid.rgb[0], seed, n);
    memset(grid.rgb[1], 0, n); /* spec: back buffer starts zeroed */
    grid.cur = 0;

    for (int i = 0; i < steps; i++) ml_grid_step(&grid, &mlrule);

    char actual[17];
    snprintf(actual, sizeof(actual), "%016" PRIx64,
             fnv1a64(grid.rgb[grid.cur], n));
    if (strcmp(actual, expected) != 0) {
      printf("FAIL  %s %dx%d steps=%d  expected %s got %s\n", rule, rows, cols,
             steps, expected, actual);
      failures++;
    }
    ml_grid_free(&grid);
  }
  fclose(f);

  if (vectors == 0) {
    fprintf(stderr, "conformance: no vectors loaded\n");
    return 1;
  }
  printf("conformance: %d/%d vectors match\n", vectors - failures, vectors);
  return failures ? 1 : 0;
}
