// Stamps Assets/Scripts/BuildInfo.cs before every player build (the dynaface
// pattern) so the About screen can prove which install a tester is actually
// running: a stale leftover build stops masquerading as fresh, and the build
// number shown matches the one App Store Connect / Google Play received. After
// a successful build the checked-in "dev" placeholders are restored, so a build
// never leaves the working tree dirty (the stamp lives in the player, not in
// git); a failed build keeps the stamp, and Reset() puts the placeholders back.
//
// The file it writes is the WP1.7 contract shape exactly:
//
//   namespace HeatonCAApp
//   {
//       public static class BuildInfo
//       {
//           public const string BuildTimeUtc = "...";
//           public const string BuildNumber = "...";
//       }
//   }
//
// and Render("dev", "dev") is byte-for-byte the checked-in placeholder. Reset()
// has no menu item on purpose; run it from a script or
//   Unity -batchmode -quit -projectPath . -executeMethod BuildInfoGenerator.Reset

using System;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

/// <summary>
/// Build callbacks that regenerate <c>Assets/Scripts/BuildInfo.cs</c>: before the
/// build with the UTC time (ISO-8601) and the active target's build number, after
/// a successful build with the "dev" placeholders again.
/// </summary>
public class BuildInfoGenerator : IPreprocessBuildWithReport, IPostprocessBuildWithReport
{
    /// <summary>Project-relative path of the generated file (owned by the HeatonCAApp assembly).</summary>
    public const string FilePath = "Assets/Scripts/BuildInfo.cs";

    /// <summary>Value of both constants when no player build has stamped the file.</summary>
    public const string Placeholder = "dev";

    private const string Tag = "[BuildInfoGenerator]";

    /// <summary>Runs first among the pre-build callbacks and last among the post-build ones.</summary>
    public int callbackOrder => 0;

    /// <summary>Writes the stamp for the target being built and re-imports the file.</summary>
    public void OnPreprocessBuild(BuildReport report)
    {
        string time = DateTime.UtcNow.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", CultureInfo.InvariantCulture);
        string number = BuildNumberFor(report.summary.platform);
        Write(time, number);
        Debug.Log($"{Tag} {FilePath}: BuildTimeUtc={time} BuildNumber={number} ({report.summary.platform})");
    }

    /// <summary>
    /// Restores the placeholders once the player is built (scripts were compiled
    /// long before this runs, so the player keeps the stamp). Unity invokes this
    /// only for a successful build.
    /// </summary>
    public void OnPostprocessBuild(BuildReport report)
    {
        Reset();
    }

    /// <summary>Restores the checked-in placeholder content ("dev" / "dev").</summary>
    public static void Reset()
    {
        Write(Placeholder, Placeholder);
        Debug.Log($"{Tag} {FilePath} reset to the \"{Placeholder}\" placeholders");
    }

    /// <summary>
    /// The store counter that applies to <paramref name="target"/>: iOS.buildNumber,
    /// Android.bundleVersionCode, or macOS.buildNumber for Standalone (macOS and
    /// Windows share the Standalone counter) and for WebGL, which has no counter
    /// of its own and borrows the Apple one so the About page reads the same
    /// everywhere. CIBuild applies HEATONCA_BUILD_NUMBER to both Apple targets
    /// before BuildPlayer runs, so this sees the value the store will see.
    /// </summary>
    public static string BuildNumberFor(BuildTarget target)
    {
        switch (target)
        {
            case BuildTarget.iOS:
                return PlayerSettings.iOS.buildNumber;
            case BuildTarget.Android:
                return PlayerSettings.Android.bundleVersionCode.ToString(CultureInfo.InvariantCulture);
            default:
                return PlayerSettings.macOS.buildNumber;
        }
    }

    /// <summary>
    /// The exact file content for the given values; with the placeholders it is
    /// the checked-in Assets/Scripts/BuildInfo.cs byte for byte (public so a test
    /// can pin both).
    /// </summary>
    public static string Render(string buildTimeUtc, string buildNumber)
    {
        var sb = new StringBuilder();
        sb.Append("// Regenerated by Assets/Editor/BuildInfoGenerator.cs before every player build\n");
        sb.Append("// (all platforms). Editor Play mode does not update it, so the values describe\n");
        sb.Append("// the last real build, not the last time the project was opened. \"dev\" is the\n");
        sb.Append("// checked-in placeholder the generator restores after a build.\n");
        sb.Append("\n");
        sb.Append("namespace HeatonCAApp\n");
        sb.Append("{\n");
        sb.Append("    /// <summary>\n");
        sb.Append("    /// Build stamp shown on the About page: when the player was built and the\n");
        sb.Append("    /// store build number it carries. Both are \"dev\" in the Editor.\n");
        sb.Append("    /// </summary>\n");
        sb.Append("    public static class BuildInfo\n");
        sb.Append("    {\n");
        sb.Append("        /// <summary>UTC build time, e.g. \"2026-09-02 14:03 UTC\", or \"dev\".</summary>\n");
        sb.Append("        public const string BuildTimeUtc = \"").Append(Escape(buildTimeUtc)).Append("\";\n");
        sb.Append("\n");
        sb.Append("        /// <summary>Store build number (HEATONCA_BUILD_NUMBER), or \"dev\".</summary>\n");
        sb.Append("        public const string BuildNumber = \"").Append(Escape(buildNumber)).Append("\";\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static void Write(string buildTimeUtc, string buildNumber)
    {
        string directory = Path.GetDirectoryName(FilePath);
        if (string.IsNullOrEmpty(directory) || !Directory.Exists(directory))
        {
            // The folder (and its .meta) belong to the app assembly; creating it here
            // would leave an unpaired folder behind. A build without the app assembly
            // is not a build worth stamping.
            throw new BuildFailedException(
                $"{Tag} {directory} does not exist; Assets/Scripts (HeatonCAApp) must be present before building");
        }

        string content = Render(buildTimeUtc, buildNumber);
        if (File.Exists(FilePath) && File.ReadAllText(FilePath) == content)
        {
            return; // already in this state; skip the write and the re-import
        }

        File.WriteAllText(FilePath, content, new UTF8Encoding(false));
        AssetDatabase.ImportAsset(FilePath);
    }

    /// <summary>Escapes a value for a C# string literal (PlayerSettings text is user-editable).</summary>
    private static string Escape(string value)
    {
        return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
