"""Generate the cross-engine conformance vectors.

Runs the reference Python engine (the mergelife library at
python/mergelife-lib) over a fixed set of rules/sizes/seeds and writes the
resulting FNV-1a 64 lattice hashes to conformance/vectors.txt. See
conformance/README.md for the full contract.

Usage (any environment with the mergelife library installed, or none at all --
the script falls back to the in-repo library source):

    python conformance/gen_vectors.py
"""

import os
import sys

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "conformance", "vectors.txt")

# rule, one steps=1 vector (localizes divergence to a single step) and one
# longer vector (catches slow drift). Non-square sizes, transposed between the
# two, so row/column swaps cannot cancel out.
RULES = [
    "e542-5f79-9341-f31e-6c6b-7f08-8773-7068",  # "Red World" (paper)
    "a07f-c000-0000-0000-0000-0000-ff80-807f",  # mostly-degenerate rule
    "6eb6-ba3d-70b4-ac6f-baae-2604-8529-8998",
    "1c48-9004-8831-41be-2804-8f50-9901-db18",
    "7e18-62ac-5c42-109e-45a1-9ff2-b7d8-64a1",  # found by the C trainer
    "2152-9b71-abb7-162a-45ff-dd03-fe15-957e",
]
CASES = [(37, 53, 1), (53, 37, 60)]  # (rows, cols, steps)


def load_reference_engine():
    """Import the mergelife library, falling back to the in-repo source."""
    try:
        import mergelife
    except ImportError:
        sys.path.insert(0, os.path.join(REPO, "python", "mergelife-lib", "src"))
        import mergelife
    return mergelife


def lcg_lattice(seed, rows, cols):
    """Spec PRNG: 32-bit LCG, one byte (state >> 24) per advance, row-major RGB."""
    state = seed & 0xFFFFFFFF
    flat = np.empty(rows * cols * 3, dtype=np.uint8)
    for i in range(flat.size):
        state = (state * 1664525 + 1013904223) & 0xFFFFFFFF
        flat[i] = state >> 24
    return flat.reshape(rows, cols, 3)


def fnv1a64(data):
    """Spec hash: FNV-1a 64-bit over raw bytes, 16 lowercase hex digits."""
    h = 0xCBF29CE484222325
    for b in bytes(data):
        h = ((h ^ b) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return "%016x" % h


def run_vector(ml, rule, rows, cols, seed, steps):
    inst = ml.new_ml_instance(rows, cols, rule)
    inst["lattice"][0]["data"] = lcg_lattice(seed, rows, cols)
    inst["lattice"][1]["data"] = np.zeros((rows, cols, 3), dtype=np.uint8)
    for _ in range(steps):
        ml.update_step(inst)
    return fnv1a64(inst["lattice"][0]["data"].tobytes())


def main():
    ml = load_reference_engine()
    lines = [
        "# MergeLife cross-engine conformance vectors.",
        "# Generated by conformance/gen_vectors.py -- do not edit by hand.",
        "# Contract: conformance/README.md",
        "# rule rows cols seed steps fnv1a64",
    ]
    seed = 1000
    for rule in RULES:
        for rows, cols, steps in CASES:
            h = run_vector(ml, rule, rows, cols, seed, steps)
            lines.append(f"{rule} {rows} {cols} {seed} {steps} {h}")
            print(f"  {rule[:9]}... {rows}x{cols} seed={seed} steps={steps} -> {h}")
            seed += 1
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nwrote {len(lines) - 4} vectors -> {OUT}")


if __name__ == "__main__":
    main()
