/*
 * MergeLife, Copyright 2018 by Jeff Heaton
 * http://www.heatonresearch.com/mergelife/
 * MIT License
 *
 * Cross-engine conformance: replay conformance/vectors.txt against the Java
 * engine. The vectors are generated by the Python reference implementation;
 * the JS and C suites replay the same file. See conformance/README.md for the
 * contract (LCG initial lattice, FNV-1a 64 hash of the final lattice).
 *
 * The LCG and hash below are independent implementations of that spec on
 * purpose -- only the engine under test is shared code.
 */
package org.heatonresearch.util;

import org.heatonresearch.mergelife.MergeLifeException;
import org.heatonresearch.mergelife.MergeLifeGrid;
import org.heatonresearch.mergelife.MergeLifeRule;
import org.junit.Assert;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

public class TestConformance {

    /** Walk up from the working directory until conformance/vectors.txt is found. */
    private File findVectors() {
        File dir = new File(System.getProperty("user.dir")).getAbsoluteFile();
        while (dir != null) {
            File candidate = new File(dir, "conformance" + File.separator + "vectors.txt");
            if (candidate.isFile()) {
                return candidate;
            }
            dir = dir.getParentFile();
        }
        throw new IllegalStateException("conformance/vectors.txt not found above " + System.getProperty("user.dir"));
    }

    /** Spec PRNG: 32-bit LCG, one byte (state >>> 24) per advance, row-major RGB. */
    private void lcgFill(int[][][] grid, int seed, int rows, int cols) {
        int state = seed;
        for (int row = 0; row < rows; row++) {
            for (int col = 0; col < cols; col++) {
                for (int ch = 0; ch < 3; ch++) {
                    state = state * 1664525 + 1013904223; // int arithmetic wraps mod 2^32
                    grid[row][col][ch] = state >>> 24;
                }
            }
        }
    }

    /** Spec hash: FNV-1a 64-bit, 16 lowercase hex digits. */
    private String fnv1a64(byte[] data) {
        long h = 0xcbf29ce484222325L;
        for (byte b : data) {
            h = (h ^ (b & 0xffL)) * 0x100000001b3L; // long arithmetic wraps mod 2^64
        }
        return String.format("%016x", h);
    }

    @Test
    public void testConformanceVectors() throws IOException, MergeLifeException {
        List<String> failures = new ArrayList<>();
        int vectors = 0;

        for (String line : Files.readAllLines(findVectors().toPath())) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }
            String[] parts = line.split("\\s+");
            String rule = parts[0];
            int rows = Integer.parseInt(parts[1]);
            int cols = Integer.parseInt(parts[2]);
            int seed = Integer.parseInt(parts[3]);
            int steps = Integer.parseInt(parts[4]);
            String expected = parts[5];
            vectors++;

            MergeLifeGrid grid = new MergeLifeGrid(rows, cols);
            lcgFill(grid.getGrid(0), seed, rows, cols);

            MergeLifeRule mlRule = new MergeLifeRule(rule);
            for (int i = 0; i < steps; i++) {
                grid.step(mlRule);
            }

            String actual = fnv1a64(grid.toBytes(grid.getCurrentGrid()));
            if (!actual.equals(expected)) {
                failures.add(rule + " " + rows + "x" + cols + " steps=" + steps
                        + " expected " + expected + " got " + actual);
            }
        }

        Assert.assertTrue("no vectors loaded", vectors > 0);
        Assert.assertTrue("conformance failures:\n" + String.join("\n", failures), failures.isEmpty());
    }
}
